package com.springmvc.pojo;

import com.springmvc.entity.Data;

import java.math.BigDecimal;

public class Food extends Data {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.id
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.name
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.price
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.img
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private String img;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.des
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private String des;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column food.shopid
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    private Integer shopid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.id
     *
     * @return the value of food.id
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.id
     *
     * @param id the value for food.id
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.name
     *
     * @return the value of food.name
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.name
     *
     * @param name the value for food.name
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.price
     *
     * @return the value of food.price
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.price
     *
     * @param price the value for food.price
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.img
     *
     * @return the value of food.img
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.img
     *
     * @param img the value for food.img
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.des
     *
     * @return the value of food.des
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.des
     *
     * @param des the value for food.des
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column food.shopid
     *
     * @return the value of food.shopid
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public Integer getShopid() {
        return shopid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column food.shopid
     *
     * @param shopid the value for food.shopid
     *
     * @mbggenerated Fri Nov 02 15:19:41 CST 2018
     */
    public void setShopid(Integer shopid) {
        this.shopid = shopid;
    }
}